
const KEY='sai_v2_db';let DB;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0))+'원';
async function init(){const s=localStorage.getItem(KEY);DB=s?JSON.parse(s):await (await fetch('data.json')).json();renderStats();renderItems();renderModeration();renderRecipes();bindNav()}
function save(){localStorage.setItem(KEY,JSON.stringify(DB))}
function all(){return [...DB.signatures,...DB.menu]}
function renderStats(){$('#stats').innerHTML=`<div class="grid"><div class="card"><div class="muted">전체 메뉴</div><div class="stat">${all().length}</div></div><div class="card"><div class="muted">사이의 추억</div><div class="stat">${DB.memories.length}</div></div><div class="card"><div class="muted">손님 레시피</div><div class="stat">${DB.recipes.length}</div></div></div>`}
function renderItems(){const items=all();$('#itemSelect').innerHTML=items.map((x,i)=>`<option value="${i}">${x.category} · ${x.name}</option>`).join('');loadItem(0);$('#itemSelect').onchange=e=>loadItem(+e.target.value)}
function loadItem(i){const x=all()[i];$('#editId').value=x.id;['name','category','price','abv','copy','recipe','score','cost'].forEach(k=>$('#'+k).value=x[k]??'')}
function saveItem(){const x=all().find(v=>v.id===$('#editId').value);['name','category','abv','copy','recipe'].forEach(k=>x[k]=$('#'+k).value);['price','score','cost'].forEach(k=>x[k]=Number($('#'+k).value||0));save();alert('메뉴가 저장되었습니다.')}
function calc(){const bp=+$(`#bottlePrice`).value,bm=+$(`#bottleMl`).value,pm=+$(`#pourMl`).value,extra=+$(`#extraCost`).value,sale=+$(`#salePrice`).value,target=+$(`#targetRate`).value;const liquid=bp/bm*pm,total=liquid+extra,rate=total/sale*100,suggest=Math.ceil((total/(target/100))/500)*500;$('#calcResult').innerHTML=`<div class="grid"><div class="card"><div class="muted">주류 원가</div><div class="stat">${money(Math.round(liquid))}</div></div><div class="card"><div class="muted">총 원가</div><div class="stat">${money(Math.round(total))}</div></div><div class="card"><div class="muted">현재 원가율</div><div class="stat">${rate.toFixed(1)}%</div></div><div class="card"><div class="muted">권장 판매가</div><div class="stat">${money(suggest)}</div></div></div>`}
function renderModeration(){$('#moderation').innerHTML=DB.memories.map(m=>`<div class="card wide"><img src="${m.image}" style="height:180px;width:100%;object-fit:cover;border-radius:14px"><h3>${m.author}</h3><p>${m.text}</p><div class="row"><button class="btn pick" data-id="${m.id}">${m.pick?'SAI PICK 해제':'SAI PICK 지정'}</button><button class="btn delete-memory" data-id="${m.id}">삭제</button></div></div>`).join('');$$('.pick').forEach(b=>b.onclick=()=>{const m=DB.memories.find(x=>x.id===b.dataset.id);m.pick=!m.pick;save();renderModeration()});$$('.delete-memory').forEach(b=>b.onclick=()=>{if(confirm('삭제할까요?')){DB.memories=DB.memories.filter(x=>x.id!==b.dataset.id);save();renderModeration();renderStats()}})}
function renderRecipes(){$('#adminRecipes').innerHTML=DB.recipes.sort((a,b)=>(b.likes+b.uses)-(a.likes+a.uses)).map((r,i)=>`<div class="card wide"><div class="eyebrow">${i===0?'현재 1위':''}</div><h3>${r.name}</h3><p>${r.note}</p><p>공감 ${r.likes} · 선택 ${r.uses}</p><p class="muted">예상 도수 ${r.abv??'-'}도 · 예상 원가 ${r.estimatedCost?money(r.estimatedCost):'-'} · 설정 가격 ${r.price?money(r.price):'-'}</p><button class="btn promote" data-id="${r.id}">정식 메뉴 후보로 표시</button></div>`).join('');$$('.promote').forEach(b=>b.onclick=()=>alert('정식 메뉴 후보로 검토 표시했습니다. 실제 메뉴 등록은 메뉴 관리에서 추가하세요.'))}
function bindNav(){$$('.admin-side button').forEach(b=>b.onclick=()=>{$$('.admin-section').forEach(s=>s.classList.add('hidden'));$('#admin-'+b.dataset.admin).classList.remove('hidden');$$('.admin-side button').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
document.addEventListener('DOMContentLoaded',()=>{init();$('#saveItem').onclick=saveItem;$('#calcBtn').onclick=calc;$('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}));a.download='sai-backup.json';a.click()};$('#resetBtn').onclick=()=>{if(confirm('초기 데이터로 되돌릴까요?')){localStorage.removeItem(KEY);location.reload()}}});
