const drinks=[
{id:'sai-night',category:'시그니처',name:'사이, 그 밤',price:'13,000원',desc:'상큼한 레몬과 검은빛 비주얼의 시그니처.',taste:'상큼·은은한 단맛',strength:'10~11도',tags:['fresh','medium','photo'],bars:[45,75,20],story:'처음 사이를 찾은 밤, 부담 없이 분위기를 시작하기 좋은 한 잔.'},
{id:'sai-temp',category:'시그니처',name:'사이의 온도',price:'14,000원',desc:'진하고 따뜻한 인상을 남기는 강한 시그니처.',taste:'진한 향·강한 여운',strength:'30~31도',tags:['smooth','strong','slow'],bars:[35,30,85]},
{id:'our-sai',category:'시그니처',name:'그날 우리 사이',price:'13,000원',desc:'자몽과 복숭아가 가볍게 이어지는 산뜻한 한 잔.',taste:'자몽·복숭아',strength:'중간',tags:['fresh','medium','photo'],bars:[65,85,25]},
{id:'sai-start',category:'시그니처',name:'사이의 시작',price:'12,000원',desc:'첫 잔에 어울리는 편안하고 밝은 맛.',taste:'가볍고 산뜻함',strength:'낮음',tags:['fresh','light','easy'],bars:[55,80,10]},
{id:'sai-end',category:'시그니처',name:'사이의 끝',price:'14,000원',desc:'긴 밤의 마지막에 천천히 즐기는 깊은 한 잔.',taste:'쌉쌀·깊은 향',strength:'높음',tags:['smooth','strong','slow'],bars:[20,25,80]},
{id:'sai-60',category:'시그니처',name:'사이 60',price:'15,000원',desc:'강렬한 도전이 필요한 밤의 60도 시그니처.',taste:'강렬하고 드라이',strength:'60도',tags:['smoky','strong','challenge'],bars:[10,20,100]},
{id:'earl-high',category:'하이볼',name:'얼그레이 하이볼',price:'13,000원',desc:'베르가못 향이 은은하게 퍼지는 향긋한 하이볼.',taste:'향긋·산뜻',strength:'6~8도',tags:['fresh','light','easy'],bars:[50,75,15]},
{id:'peach-high',category:'하이볼',name:'피치 하이볼',price:'13,000원',desc:'복숭아의 달콤함과 탄산감.',taste:'달콤·청량',strength:'6~8도',tags:['sweet','light','photo'],bars:[85,65,10]},
{id:'junebug',category:'칵테일',name:'준벅',price:'14,000원',desc:'멜론과 열대과일의 달콤하고 화사한 칵테일.',taste:'달콤·트로피컬',strength:'중간',tags:['sweet','medium','photo'],bars:[90,55,25]},
{id:'faust',category:'칵테일',name:'파우스트',price:'가격 문의',desc:'럼 베이스의 강렬하고 깊은 칵테일.',taste:'강렬·묵직',strength:'높음',tags:['smooth','strong','challenge'],bars:[25,20,90]},
{id:'kahlua',category:'칵테일',name:'깔루아 밀크',price:'가격 문의',desc:'커피 리큐르와 우유의 부드러운 달콤함.',taste:'커피·크리미',strength:'낮음',tags:['sweet','light','easy'],bars:[90,20,15]},
{id:'longisland',category:'칵테일',name:'롱아일랜드 아이스티',price:'13,000원',desc:'차 없이도 아이스티를 닮은 강한 클래식.',taste:'상큼·콜라·강함',strength:'12~14도',tags:['fresh','strong','challenge'],bars:[45,70,70]},
{id:'laphroaig10',category:'위스키',name:'라프로익 10년',price:'14,000원',desc:'바다, 소독약, 모닥불을 떠올리게 하는 강렬한 피트.',taste:'피트·요오드·바다',strength:'강함',tags:['smoky','strong','challenge'],bars:[10,15,95],origin:'스코틀랜드 아일라',type:'피트 싱글몰트'},
{id:'ardbeg10',category:'위스키',name:'아드벡 10년',price:'14,000원',desc:'짙은 연기 속 감귤과 바닐라가 숨어 있는 아일라 몰트.',taste:'연기·감귤·바닐라',strength:'강함',tags:['smoky','strong','slow'],bars:[20,30,95],origin:'스코틀랜드 아일라',type:'피트 싱글몰트'},
{id:'glenfiddich12',category:'위스키',name:'글렌피딕 12년',price:'가격 문의',desc:'배와 사과 향이 편안한 싱글몰트 입문 대표.',taste:'배·사과·가벼운 오크',strength:'중간',tags:['fresh','medium','easy'],bars:[45,70,35],origin:'스코틀랜드 스페이사이드',type:'싱글몰트'},
{id:'macallan-sherry12',category:'위스키',name:'맥캘란 12년 셰리 오크',price:'샷 18,000원 · 바틀 329,000원',desc:'건과일과 스파이스가 풍성한 정통 셰리 스타일.',taste:'건포도·계피·오크',strength:'중강',tags:['sweet','strong','slow'],bars:[75,25,65],origin:'스코틀랜드 스페이사이드',type:'셰리 싱글몰트'},
{id:'glenallachie15',category:'위스키',name:'글렌알라키 15년',price:'샷 20,000원 · 바틀 389,000원',desc:'짙은 건과일과 초콜릿이 겹치는 농밀한 셰리 위스키.',taste:'건포도·초콜릿·스파이스',strength:'중강',tags:['sweet','strong','slow'],bars:[85,20,65],origin:'스코틀랜드 스페이사이드',type:'셰리 싱글몰트'},
{id:'glendronach12',category:'위스키',name:'글렌드로낙 12년',price:'샷 15,000원 · 바틀 249,000원',desc:'건과일과 초콜릿의 풍성함으로 사랑받는 셰리 입문.',taste:'건과일·초콜릿·오크',strength:'중간',tags:['sweet','medium','slow'],bars:[80,20,55],origin:'스코틀랜드 하이랜드',type:'셰리 싱글몰트'},
{id:'lagavulin8',category:'위스키',name:'라가불린 8년',price:'샷 15,000원 · 바틀 249,000원',desc:'건조한 연기와 후추, 바다의 짠맛이 선명한 피트.',taste:'드라이 피트·후추·바다',strength:'강함',tags:['smoky','strong','slow'],bars:[10,15,90],origin:'스코틀랜드 아일라',type:'피트 싱글몰트'},
{id:'kavalan-select',category:'위스키',name:'카발란 디스틸러리 셀렉트',price:'샷 15,000원 · 바틀 289,000원',desc:'열대과일과 바닐라가 부드럽게 이어지는 대만 위스키.',taste:'열대과일·바닐라',strength:'중간',tags:['smooth','medium','easy'],bars:[60,65,40],origin:'대만',type:'싱글몰트'},
{id:'hibiki-harmony',category:'위스키',name:'히비키 하모니',price:'샷 20,000원 · 바틀 330,000원',desc:'꽃, 꿀, 은은한 오크가 정교하게 이어지는 일본 블렌디드.',taste:'꽃·꿀·오크',strength:'중간',tags:['smooth','medium','slow'],bars:[55,55,40],origin:'일본',type:'블렌디드'},
{id:'yamazaki',category:'위스키',name:'야마자키',price:'샷 33,000원 · 재고 상시 문의',desc:'섬세한 과일과 향신료가 겹치는 일본 싱글몰트.',taste:'과일·향신료·오크',strength:'중강',tags:['smooth','strong','slow'],bars:[60,50,55],origin:'일본',type:'싱글몰트'},
{id:'grant15',category:'위스키',name:'글렌그란트 15년',price:'샷 20,000원 · 바틀 370,000원',desc:'과일과 꿀, 산뜻한 스파이스가 균형 잡힌 몰트.',taste:'배·꿀·스파이스',strength:'중간',tags:['fresh','medium','slow'],bars:[55,70,45],origin:'스코틀랜드 스페이사이드',type:'싱글몰트'},
{id:'remy-vsop',category:'꼬냑·데킬라',name:'레미마틴 VSOP',price:'샷 15,000원 · 바틀 279,000원',desc:'잘 익은 과일과 바닐라, 부드러운 오크의 꼬냑.',taste:'과일·바닐라·오크',strength:'중강',tags:['smooth','strong','slow'],bars:[65,45,55],origin:'프랑스 코냑',type:'꼬냑'},
{id:'818',category:'꼬냑·데킬라',name:'818 레포사도',price:'가격 문의',desc:'바닐라와 캐러멜이 부드럽게 느껴지는 레포사도.',taste:'바닐라·아가베',strength:'강함',tags:['smooth','strong','challenge'],bars:[55,30,70]},
{id:'shirley',category:'논알콜',name:'셜리 템플',price:'13,000원',desc:'달콤하고 산뜻한 클래식 논알콜.',taste:'달콤·상큼',strength:'0도',tags:['sweet','light','photo'],bars:[80,70,0]},
{id:'sai-icedtea',category:'논알콜',name:'사이 아이스티',price:'13,000원',desc:'자몽과 레몬의 산뜻한 사이 시그니처 논알콜.',taste:'자몽·레몬',strength:'0도',tags:['fresh','light','easy'],bars:[55,85,0]}
];
const categories=['전체','시그니처','하이볼','칵테일','위스키','꼬냑·데킬라','논알콜'];
const seedMessages={
'sai-night':['오늘은 너무 서두르지 않아도 괜찮아요.','사진보다 실제 색이 더 기억에 남았어요.'],
'glendronach12':['향부터 천천히 맡아보세요. 마지막 한 모금이 가장 좋아요.','힘든 하루 끝에 건과일 향이 작은 위로가 됐어요.'],
'laphroaig10':['첫 향에 놀라도 한 모금 뒤까지 기다려보세요.','모닥불 옆 바닷가를 상상하며 마셔보세요.'],
'hibiki-harmony':['조용한 날 천천히 마시면 더 예쁜 술이에요.'],
'default':['오늘의 한 잔이 좋은 기억으로 남기를 바라요.','천천히, 향부터 만나보세요.']};
const reviews={
'glendronach12':['달콤하지만 가볍지 않아서 좋았어요.','셰리 위스키 입문으로 딱 좋았습니다.'],
'laphroaig10':['진짜 소독약 향인데 이상하게 또 생각나요.','피트 처음이면 조금씩 천천히 추천!'],
'sai-night':['사진도 예쁘고 첫 잔으로 부담 없었어요.'],
'default':['설명과 실제 맛이 잘 맞았어요.','다음에도 다시 주문하고 싶은 한 잔.']};
let currentCategory='전체', selected={}, leaveType='drink', lastLeave='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function renderTabs(){const wrap=$('#categoryTabs');wrap.innerHTML=categories.map(c=>`<button class="${c===currentCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');wrap.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.cat;renderTabs();renderMenu()})}
function renderMenu(){const list=currentCategory==='전체'?drinks:drinks.filter(d=>d.category===currentCategory);$('#menuList').innerHTML=list.map(d=>`<button class="menu-item" data-id="${d.id}"><div><h3>${d.name}</h3><p>${d.desc}</p></div><strong>${d.price}</strong></button>`).join('');$('#menuList').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDrink(b.dataset.id))}
function messagesFor(id){const saved=JSON.parse(localStorage.getItem('sai_public_batons')||'[]').filter(x=>x.drinkId===id);return [...saved.map(x=>x.text),...(seedMessages[id]||seedMessages.default)]}
function openDrink(id){const d=drinks.find(x=>x.id===id);const r=reviews[id]||reviews.default;const m=messagesFor(id);$('#modalContent').innerHTML=`<div class="detail-title"><p class="eyebrow">${d.category.toUpperCase()}</p><h1>${d.name}</h1><strong>${d.price}</strong><p>${d.desc}</p></div><div class="taste-bars"><div class="bar-row"><span>달콤함</span><div class="bar"><i style="width:${d.bars[0]}%"></i></div><b>${d.bars[0]}</b></div><div class="bar-row"><span>산뜻함</span><div class="bar"><i style="width:${d.bars[1]}%"></i></div><b>${d.bars[1]}</b></div><div class="bar-row"><span>도수감</span><div class="bar"><i style="width:${d.bars[2]}%"></i></div><b>${d.bars[2]}</b></div></div><div class="library-meta"><span>${d.taste}</span><span>${d.strength}</span>${d.origin?`<span>${d.origin}</span>`:''}</div><div class="review-block"><h3>마셔본 손님들의 한줄평</h3>${r.map((x,i)=>`<div class="review"><b>★★★★★ · 익명 손님</b><p>${x}</p></div>`).join('')}</div><div class="baton-block"><h3>이 술이 전하는 이야기</h3><div class="review"><b>어느 날의 손님</b><p>“${m[Math.floor(Math.random()*m.length)]}”</p></div></div><button class="primary full order-btn" id="orderNow">이 메뉴 주문하기</button>`;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false');$('#orderNow').onclick=()=>orderDrink(d)}
function orderDrink(d){localStorage.setItem('sai_pending_baton',JSON.stringify({drinkId:d.id,drinkName:d.name,orderedAt:new Date().toISOString()}));const arr=messagesFor(d.id);const msg=arr[Math.floor(Math.random()*arr.length)];$('#modalContent').innerHTML=`<div class="story-reveal"><p class="eyebrow">한 잔의 바통</p><h2>${d.name} 주문이 전달됐어요.</h2><p class="quote">“${msg}”</p><small>이 술을 먼저 마신 누군가가 다음 사람에게 남긴 이야기</small><div style="height:24px"></div><p>잠시 후 당신의 잔이 준비됩니다.<br>오늘의 경험은 다음 방문에 이어주세요.</p><button class="secondary full" onclick="document.querySelector('#modalClose').click()">확인</button></div>`}
$('#modalClose').onclick=()=>{$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')};$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modalClose').click()};
function checkGate(){const pending=JSON.parse(localStorage.getItem('sai_pending_baton')||'null');if(!pending)return;$('#pendingDrink').innerHTML=`지난 주문 · <b>${pending.drinkName}</b>`;$('#gate').classList.remove('hidden')}
const prompts=['다음 사람에게 추천한다면?','어떤 날 잘 어울릴까요?','향을 맡았을 때 느낌은?','오늘의 나에게 한마디'];$('#promptChips').innerHTML=prompts.map(x=>`<button>${x}</button>`).join('');$('#promptChips').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#promptChips button.selected')?.classList.remove('selected');b.classList.add('selected');$('#batonText').placeholder=b.textContent+' (5자 이상)' });$('#batonText').oninput=e=>$('#batonCount').textContent=e.target.value.length;
$('#submitBaton').onclick=()=>{const text=$('#batonText').value.trim();if(text.length<5)return showToast('5자 이상 남겨주세요.');const pending=JSON.parse(localStorage.getItem('sai_pending_baton'));const privacy=document.querySelector('input[name=privacy]:checked').value;const entry={...pending,text,privacy,createdAt:new Date().toISOString()};const all=JSON.parse(localStorage.getItem('sai_all_batons')||'[]');all.unshift(entry);localStorage.setItem('sai_all_batons',JSON.stringify(all));if(privacy!=='private'){const pub=JSON.parse(localStorage.getItem('sai_public_batons')||'[]');pub.unshift(entry);localStorage.setItem('sai_public_batons',JSON.stringify(pub))}localStorage.removeItem('sai_pending_baton');$('#gate').classList.add('hidden');showToast('이야기가 다음 잔으로 이어졌어요.')};
$$('.choices button').forEach(b=>b.onclick=()=>{const group=b.closest('.choices').dataset.group;selected[group]=b.dataset.value;b.closest('.choices').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))});
$('#recommendBtn').onclick=()=>{if(Object.keys(selected).length<3)return showToast('세 가지 취향을 모두 선택해주세요.');const scored=drinks.map(d=>({...d,score:d.tags.reduce((n,t)=>n+(Object.values(selected).includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score);const d=scored[0];$('#recommendResult').innerHTML=`<div class="result-card"><p class="eyebrow">OWNER'S SELECTION</p><h2>${d.name}</h2><p>선택하신 <b>${label(selected.taste)}</b>, <b>${label(selected.strength)}</b>, <b>${label(selected.mood)}</b> 기준을 함께 만족하는 메뉴예요. 사이에서 실제로 사용하는 추천 기준으로 골랐습니다.</p><strong>${d.price}</strong><div style="height:14px"></div><button class="secondary full" data-result="${d.id}">자세히 보기</button></div>`;$('#recommendResult [data-result]').onclick=()=>openDrink(d.id)};
function label(x){return({sweet:'달콤한 맛',fresh:'산뜻한 맛',smooth:'부드러운 맛',smoky:'스모키한 향',light:'가벼운 도수감',medium:'적당한 도수감',strong:'확실한 도수감',easy:'편안한 분위기',photo:'예쁜 한 잔',challenge:'새로운 도전',slow:'천천히 음미'})[x]}
function renderLibrary(){const data=drinks.filter(d=>d.origin);$('#libraryList').innerHTML=data.map(d=>`<article class="library-card" data-lib="${d.id}"><h3>${d.name}</h3><p>${d.story||d.desc}</p><div class="library-meta"><span>${d.origin}</span><span>${d.type}</span><span>${d.taste}</span></div></article>`).join('');$('#libraryList').querySelectorAll('[data-lib]').forEach(x=>x.onclick=()=>openDrink(x.dataset.lib))}
$('#leaveTypes').querySelectorAll('button').forEach(b=>b.onclick=()=>{leaveType=b.dataset.type;$('#leaveTypes button').forEach(x=>x.classList.toggle('selected',x===b))});$('#leaveDrink').innerHTML+=[...drinks].sort((a,b)=>a.name.localeCompare(b.name,'ko')).map(d=>`<option value="${d.name}">${d.name}</option>`).join('');
$('#saveLeave').onclick=()=>{const text=$('#leaveText').value.trim();if(text.length<3)return showToast('내용을 조금만 더 적어주세요.');const entry={type:leaveType,drink:$('#leaveDrink').value,nickname:$('#leaveNickname').value.trim()||'익명',text,public:$('#leavePublic').checked,createdAt:new Date().toISOString()};const all=JSON.parse(localStorage.getItem('sai_feedback')||'[]');all.unshift(entry);localStorage.setItem('sai_feedback',JSON.stringify(all));lastLeave=text;$('#leaveSuccess').classList.remove('hidden');showToast('사이에 이야기가 남았습니다.')};$('#copyLeave').onclick=async()=>{try{await navigator.clipboard.writeText(lastLeave);showToast('글을 복사했어요.')}catch{showToast('길게 눌러 글을 복사해주세요.')}};
renderTabs();renderMenu();renderLibrary();checkGate();
