const DEFAULT_DRINKS = [
  {id:'sai-night',category:'시그니처',name:'사이, 그 밤',price:13000,abv:'10~11도',desc:'레몬의 산뜻함과 검은빛의 반전이 오래 남는 사이의 대표 시그니처.',recommended:true,active:true,tags:['fresh','medium','photo']},
  {id:'sai-temp',category:'시그니처',name:'사이의 온도',price:14000,abv:'30~31도',desc:'짙고 따뜻한 인상으로 천천히 온도가 올라오는 강한 시그니처.',recommended:false,active:true,tags:['smooth','strong','slow']},
  {id:'our-sai',category:'시그니처',name:'그날 우리 사이',price:13000,abv:'',desc:'자몽과 복숭아가 부드럽게 이어지는 화사하고 산뜻한 한 잔.',recommended:false,active:true,tags:['fresh','medium','photo']},
  {id:'passed-sai',category:'시그니처',name:'사이 스친 우리',price:13000,abv:'',desc:'스쳐 지나간 인연처럼 가볍고 은은하게 남는 시그니처.',recommended:false,active:true,tags:['fresh','medium','easy']},
  {id:'sai-start',category:'시그니처',name:'사이의 시작',price:12000,abv:'',desc:'첫 잔으로 부담 없이 시작하기 좋은 밝고 편안한 맛.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'sai-end',category:'시그니처',name:'사이의 끝',price:14000,abv:'',desc:'긴 밤의 마지막에 천천히 마시기 좋은 깊은 한 잔.',recommended:false,active:true,tags:['smooth','strong','slow']},
  {id:'sai-60',category:'시그니처',name:'사이 60',price:15000,abv:'60도',desc:'론 디아즈 오버프루프 럼의 강렬함을 담은 도전적인 시그니처.',recommended:false,active:true,tags:['smoky','strong','challenge']},
  {id:'sai-toktok',category:'시그니처',name:'사이 톡톡',price:0,abv:'6~8도',desc:'원하는 위스키와 음료를 골라 만드는 사이만의 커스텀 하이볼.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'longisland',category:'칵테일',name:'롱아일랜드 아이스티',price:13000,abv:'12~14도',desc:'여러 베이스가 조화롭게 이어지는 상큼하고 강렬한 클래식.',recommended:false,active:true,tags:['fresh','strong','challenge']},
  {id:'longbeach',category:'칵테일',name:'롱비치 아이스티',price:14000,abv:'12~14도',desc:'크랜베리의 산뜻함이 더해진 붉고 화사한 아이스티 칵테일.',recommended:false,active:true,tags:['fresh','medium','photo']},
  {id:'tokyo-icedtea',category:'칵테일',name:'도쿄 아이스티',price:14000,abv:'12~14도',desc:'멜론 향과 시트러스가 선명한 초록빛 아이스티 칵테일.',recommended:false,active:true,tags:['sweet','medium','photo']},
  {id:'tequila-sunrise',category:'칵테일',name:'데킬라 선라이즈',price:13000,abv:'',desc:'오렌지와 그레나딘이 해 뜨는 순간처럼 층을 이루는 클래식.',recommended:false,active:true,tags:['sweet','medium','photo']},
  {id:'faust',category:'칵테일',name:'파우스트',price:14000,abv:'',desc:'진하고 강한 럼의 매력을 느낄 수 있는 사이 추천 칵테일.',recommended:true,active:true,tags:['sweet','strong','challenge']},
  {id:'melon-crush',category:'칵테일',name:'멜론 크러쉬',price:14000,abv:'',desc:'멜론의 달콤함과 시원한 질감이 매력적인 칵테일.',recommended:false,active:true,tags:['sweet','medium','photo']},
  {id:'junebug',category:'칵테일',name:'준벅',price:14000,abv:'',desc:'멜론과 열대과일이 풍성하게 이어지는 인기 칵테일.',recommended:false,active:true,tags:['sweet','medium','photo']},
  {id:'gin-tonic',category:'칵테일',name:'진토닉',price:11000,abv:'',desc:'진의 향과 토닉의 청량함을 가장 깔끔하게 즐기는 한 잔.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'bombay-tonic',category:'칵테일',name:'봄베이 진토닉',price:13000,abv:'',desc:'봄베이 사파이어의 화사한 향을 살린 추천 진토닉.',recommended:true,active:true,tags:['fresh','medium','easy']},
  {id:'vodka-cran',category:'칵테일',name:'보드카 크랜베리',price:13000,abv:'10~12도',desc:'크랜베리의 새콤달콤함과 보드카가 가볍게 어우러지는 한 잔.',recommended:false,active:true,tags:['fresh','medium','easy']},
  {id:'black-russian',category:'칵테일',name:'블랙 러시안',price:14000,abv:'28~30도',desc:'커피 리큐르의 달콤함과 보드카의 묵직함이 선명한 칵테일.',recommended:false,active:true,tags:['sweet','strong','slow']},
  {id:'godfather',category:'칵테일',name:'갓파더',price:14000,abv:'',desc:'위스키와 아마레또가 묵직하고 달콤하게 이어지는 추천 칵테일.',recommended:true,active:true,tags:['sweet','strong','slow']},
  {id:'godmother',category:'칵테일',name:'갓마더',price:14000,abv:'',desc:'보드카와 아마레또의 매끈하고 달콤한 조합.',recommended:false,active:true,tags:['sweet','strong','slow']},
  {id:'catharsis',category:'칵테일',name:'카타르시스',price:14000,abv:'',desc:'달콤함 뒤에 강한 여운을 남기는 개성 있는 칵테일.',recommended:false,active:true,tags:['sweet','strong','challenge']},
  {id:'late-burn',category:'칵테일',name:'늦은 화상',price:15000,abv:'50도',desc:'늦게 찾아오는 강렬한 열감과 긴 여운을 가진 고도수 칵테일.',recommended:false,active:true,tags:['smoky','strong','challenge']},
  {id:'kahlua-milk',category:'칵테일',name:'깔루아 밀크',price:13000,abv:'',desc:'커피와 우유의 부드러운 달콤함으로 사랑받는 추천 칵테일.',recommended:true,active:true,tags:['sweet','light','easy']},
  {id:'earl-high',category:'하이볼',name:'얼그레이 하이볼',price:13000,abv:'6~8도',desc:'베르가못 향이 은은하게 퍼지는 향긋한 하이볼.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'peach-high',category:'하이볼',name:'피치 하이볼',price:13000,abv:'6~8도',desc:'복숭아의 달콤함과 탄산감이 가볍게 이어지는 하이볼.',recommended:false,active:true,tags:['sweet','light','photo']},
  {id:'malibu-high',category:'하이볼',name:'말리부 하이볼',price:13000,abv:'6~8도',desc:'코코넛의 달콤한 향과 탄산이 어우러진 휴양지 같은 한 잔.',recommended:false,active:true,tags:['sweet','light','easy']},
  {id:'whisky-night',category:'하이볼',name:'위스키 밤',price:14000,abv:'6~8도',desc:'밤처럼 깊은 위스키 향을 탄산과 함께 편하게 즐기는 하이볼.',recommended:false,active:true,tags:['smooth','medium','slow']},
  {id:'sai-icedtea',category:'논알콜',name:'사이 아이스티',price:13000,abv:'논알콜',desc:'자몽과 레몬의 산뜻함을 담은 사이 시그니처 논알콜.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'shirley',category:'논알콜',name:'셜리 템플',price:13000,abv:'논알콜',desc:'달콤하고 산뜻한 붉은빛의 클래식 논알콜 칵테일.',recommended:false,active:true,tags:['sweet','light','photo']},
  {id:'earl-zero',category:'논알콜',name:'얼그레이 하이볼',price:13000,abv:'논알콜',desc:'얼그레이 향과 탄산을 가볍게 즐기는 논알콜 하이볼.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'lemonade',category:'논알콜',name:'레몬에이드',price:11000,abv:'논알콜',desc:'상큼하고 시원하게 즐기는 클래식 레몬에이드.',recommended:false,active:true,tags:['fresh','light','easy']},
  {id:'peach-zero',category:'논알콜',name:'피치 하이볼',price:12000,abv:'논알콜',desc:'복숭아의 달콤함과 청량함을 담은 논알콜 하이볼.',recommended:false,active:true,tags:['sweet','light','photo']},
  {id:'summer-crush',category:'논알콜',name:'썸머 크러쉬',price:13000,abv:'논알콜',desc:'여름 과일의 상큼함을 시원하게 담은 논알콜 칵테일.',recommended:false,active:true,tags:['fresh','light','photo']},
  {id:'ardbeg',category:'위스키',name:'아드벡',price:14000,abv:'',desc:'짙은 연기와 시트러스, 바닐라가 공존하는 아일라 몰트.',recommended:false,active:true,tags:['smoky','strong','slow']},
  {id:'laphroaig',category:'위스키',name:'라프로익',price:14000,abv:'',desc:'바다와 모닥불을 떠올리게 하는 강렬한 피트 위스키.',recommended:false,active:true,tags:['smoky','strong','challenge']},
  {id:'jw-green',category:'위스키',name:'조니워커 그린',price:16000,abv:'',desc:'몰트 위스키의 균형과 은은한 스모키함이 돋보이는 블렌디드 몰트.',recommended:false,active:true,tags:['smooth','medium','slow']},
  {id:'glenmorangie',category:'위스키',name:'글렌모렌지',price:15000,abv:'',desc:'감귤과 바닐라의 화사함으로 시작하기 좋은 싱글몰트.',recommended:false,active:true,tags:['fresh','medium','easy']},
  {id:'glenallachie',category:'위스키',name:'글렌알라키',price:16000,abv:'',desc:'풍성한 셰리와 건과일의 진한 단맛을 가진 싱글몰트.',recommended:false,active:true,tags:['sweet','medium','slow']},
  {id:'monkey-shoulder',category:'위스키',name:'몽키 숄더',price:13000,abv:'',desc:'바닐라와 몰트의 부드러움으로 편하게 즐기는 블렌디드 몰트.',recommended:false,active:true,tags:['smooth','medium','easy']},
  {id:'wild-turkey',category:'위스키',name:'와일드 터키',price:13000,abv:'',desc:'바닐라와 캐러멜, 스파이스가 선명한 버번 위스키.',recommended:false,active:true,tags:['sweet','strong','challenge']},
  {id:'tequila-shot',category:'꼬냑·데킬라',name:'데킬라 샷',price:5000,abv:'',desc:'깔끔하고 강렬하게 즐기는 데킬라 한 잔.',recommended:false,active:true,tags:['strong','challenge']},
  {id:'sai-bet-tequila',category:'꼬냑·데킬라',name:'사이 내기 데킬라',price:15000,abv:'',desc:'함께 즐기는 데킬라 5잔 세트.',recommended:false,active:true,tags:['strong','challenge']},
  {id:'guinness',category:'맥주',name:'기네스',price:11000,abv:'',desc:'부드러운 거품과 로스팅 향이 매력적인 스타우트.',recommended:false,active:true,tags:['smooth','medium','slow']},
  {id:'nacho',category:'푸드',name:'나쵸',price:5000,abv:'',desc:'칵테일과 가볍게 곁들이기 좋은 바삭한 나쵸.',recommended:false,active:true,tags:[]},
  {id:'popcorn-refill',category:'푸드',name:'팝콘 리필',price:1000,abv:'',desc:'사이에서 가볍게 이어가는 팝콘 리필.',recommended:false,active:true,tags:[]}
];
const CAPACITY=14, MIN_ATMOSPHERE=6, CATEGORY_ORDER=['시그니처','칵테일','하이볼','논알콜','위스키','꼬냑·데킬라','맥주','푸드'];
let currentCategory='전체',selected={};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const formatPrice=n=>Number(n)===0?'가격 선택':`${Number(n).toLocaleString('ko-KR')}원`;
function loadDrinks(){try{const saved=JSON.parse(localStorage.getItem('sai_menu_v2'));return Array.isArray(saved)&&saved.length?saved:structuredClone(DEFAULT_DRINKS)}catch(e){return structuredClone(DEFAULT_DRINKS)}}
let drinks=loadDrinks();
function saveDrinks(){localStorage.setItem('sai_menu_v2',JSON.stringify(drinks));renderTabs();renderMenu();renderAdminMenu()}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
function finishSplash(){if($('#splash').classList.contains('done'))return;$('#splash').classList.add('done');$('#app').classList.remove('app-entering');$('#app').classList.add('app-ready')}
$('#skipSplash').onclick=finishSplash;setTimeout(finishSplash,3600);
function categories(){return ['전체',...CATEGORY_ORDER.filter(c=>drinks.some(x=>x.category===c)),...new Set(drinks.map(x=>x.category).filter(c=>!CATEGORY_ORDER.includes(c)))]}
function renderTabs(){const w=$('#categoryTabs');w.innerHTML=categories().map(c=>`<button class="${c===currentCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');w.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentCategory=b.dataset.cat;renderTabs();renderMenu()})}
function renderMenu(){let list=drinks.filter(d=>d.active!==false);if(currentCategory!=='전체')list=list.filter(d=>d.category===currentCategory);let last='';$('#menuList').innerHTML=list.map(d=>{const heading=currentCategory==='전체'&&last!==d.category?`<div class="menu-section-title">${d.category}</div>`:'';last=d.category;return `${heading}<button class="menu-item" data-id="${d.id}"><div><h3>${d.name}${d.recommended?'<span class="star">★ 추천</span>':''}</h3><p>${d.desc}</p><div class="menu-badges">${d.abv?`<span class="menu-badge">${d.abv}</span>`:''}</div></div><strong>${formatPrice(d.price)}</strong></button>`}).join('')||'<p class="admin-note">현재 표시할 메뉴가 없습니다.</p>';$('#menuList').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openDrink(b.dataset.id))}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function openDrink(id){const d=drinks.find(x=>x.id===id);openModal(`<div class="detail-title"><p class="eyebrow">${d.category.toUpperCase()}</p><h2>${d.name}</h2><strong>${formatPrice(d.price)}</strong><div class="menu-badges">${d.recommended?'<span class="menu-badge recommended">사이 추천</span>':''}${d.abv?`<span class="menu-badge">${d.abv}</span>`:''}</div><p>${d.desc}</p></div><div class="seat-status">오늘의 한 잔이 좋은 기억으로 남기를 바라요.</div>`)}
$$('[data-item-id]').forEach(x=>x.onclick=()=>openDrink(x.dataset.itemId));
$$('.choices button').forEach(b=>b.onclick=()=>{const group=b.closest('.choices').dataset.group;selected[group]=b.dataset.value;b.closest('.choices').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b))});
$('#recommendBtn').onclick=()=>{if(Object.keys(selected).length<3)return showToast('세 가지 취향을 모두 선택해주세요.');const candidates=drinks.filter(d=>d.active!==false&&d.category!=='푸드');const scores=candidates.map(d=>({...d,score:(d.tags||[]).filter(t=>Object.values(selected).includes(t)).length+(d.recommended?.25:0)})).sort((a,b)=>b.score-a.score);const d=scores[0];$('#recommendResult').innerHTML=`<div class="result-card"><p class="eyebrow">TODAY'S SELECTION</p><h2>${d.name}</h2><p>지금 선택한 취향과 가장 가까운 한 잔입니다.</p><strong>${formatPrice(d.price)}</strong><div style="height:15px"></div><button class="secondary full" id="resultDetail">자세히 보기</button></div>`;$('#resultDetail').onclick=()=>openDrink(d.id)};
function getGuestCount(){return Math.max(0,Math.min(CAPACITY,Number(localStorage.getItem('sai_guest_count')??8)))}
function atmosphereText(n){if(n>=CAPACITY)return{title:'오늘도 모든 자리가 채워졌습니다.',preview:'오늘도 사이는 따뜻한 이야기들로 가득 찼어요',body:'오늘 함께해 주신 모든 분들께 감사합니다. 자리가 생기면 바로 알려드릴게요.'};if(n>=12)return{title:'오늘의 사이가 가장 빛나는 순간',preview:'지금, 사이의 밤이 가장 뜨겁게 이어지고 있어요',body:'늦은 밤의 분위기를 가장 잘 느낄 수 있는 시간입니다.'};if(n>=9)return{title:'자연스럽게 이야기가 오가는 밤',preview:'지금, 새로운 이야기들이 이어지고 있어요',body:'혼자 오셔도 자연스럽게 어울리기 좋은 분위기예요.'};return{title:'도란도란 이야기가 이어지는 밤',preview:'지금, 사이에 이야기가 모이고 있어요',body:'편안하게 한 잔과 대화를 즐기기 좋은 시간입니다.'}}
function renderAtmosphere(){const n=getGuestCount(),card=$('#atmosphereCard');if(n<MIN_ATMOSPHERE){card.classList.add('hidden');return}const t=atmosphereText(n);card.classList.remove('hidden');$('#atmospherePreview').textContent=t.preview}
function openAtmosphere(){const n=getGuestCount(),t=atmosphereText(n),left=CAPACITY-n;if(n>=CAPACITY){openModal(`<div class="atmosphere-detail"><p class="eyebrow">TODAY AT SAI</p><h2 class="soldout-title">${t.title}</h2><p>${t.body}</p><div class="seat-status">현재 만석입니다.</div><p class="notify-copy">사이는 21:00부터 06:00까지 오래 이어집니다. 빈자리가 생기는 순간 알림을 받을 수 있어요.</p><button id="notifySeat" class="primary full">빈자리 알림 받기</button></div>`);$('#notifySeat').onclick=requestSeatNotification}else{openModal(`<div class="atmosphere-detail"><p class="eyebrow">TODAY AT SAI</p><h2>${t.title}</h2><p>${t.body}</p><div class="seat-status">현재 ${left}자리 남았습니다.</div></div>`)}}
$('#atmosphereCard').onclick=openAtmosphere;
async function requestSeatNotification(){localStorage.setItem('sai_seat_notify','on');if('Notification'in window&&Notification.permission==='default'){try{await Notification.requestPermission()}catch(e){}}showToast('빈자리가 생기면 알려드릴게요.');closeModal()}
function maybeNotify(oldCount,newCount){if(oldCount>=CAPACITY&&newCount<CAPACITY&&localStorage.getItem('sai_seat_notify')==='on'){const left=CAPACITY-newCount;const msg=`방금 자리가 생겼습니다. 현재 ${left}자리 이용 가능합니다.`;if('Notification'in window&&Notification.permission==='granted'){new Notification('🌙 사이 빈자리 알림',{body:msg})}showToast(`🔔 ${msg}`);localStorage.removeItem('sai_seat_notify')}}
$('#adminBtn').onclick=()=>{const n=getGuestCount();$('#guestCount').value=n;$('#guestCountLabel').textContent=n;renderAdminMenu();$('#adminPanel').classList.remove('hidden')};$('#adminClose').onclick=()=>$('#adminPanel').classList.add('hidden');$('#adminPanel').onclick=e=>{if(e.target.id==='adminPanel')$('#adminPanel').classList.add('hidden')};$('#guestCount').oninput=e=>$('#guestCountLabel').textContent=e.target.value;$('#setQuiet').onclick=()=>setSlider(5);$('#setBusy').onclick=()=>setSlider(10);$('#setFull').onclick=()=>setSlider(14);function setSlider(n){$('#guestCount').value=n;$('#guestCountLabel').textContent=n}
$('#saveGuestCount').onclick=()=>{const old=getGuestCount(),n=Number($('#guestCount').value);localStorage.setItem('sai_guest_count',n);renderAtmosphere();maybeNotify(old,n);$('#adminPanel').classList.add('hidden');showToast(n===14?'오늘의 사이를 만석으로 표시했어요.':'현재 분위기를 반영했어요.')}
$('#simulateSeat').onclick=()=>{localStorage.setItem('sai_guest_count',14);localStorage.setItem('sai_seat_notify','on');renderAtmosphere();setTimeout(()=>{const old=14,newCount=12;localStorage.setItem('sai_guest_count',newCount);renderAtmosphere();maybeNotify(old,newCount)},900);showToast('만석 → 2자리 발생을 테스트합니다.')}
function renderAdminMenu(){const target=$('#adminMenuList');if(!target)return;target.innerHTML=drinks.map(d=>`<div class="admin-menu-item ${d.active===false?'off':''}"><div><b>${d.name}${d.recommended?' ★':''}</b><small>${d.category} · ${formatPrice(d.price)}${d.abv?' · '+d.abv:''}${d.active===false?' · 숨김':''}</small></div><div class="admin-menu-actions"><button data-edit="${d.id}">수정</button><button data-toggle="${d.id}">${d.active===false?'판매':'숨김'}</button></div></div>`).join('');target.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openMenuEditor(b.dataset.edit));target.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const d=drinks.find(x=>x.id===b.dataset.toggle);d.active=d.active===false;saveDrinks();showToast(d.active?'메뉴를 다시 표시했어요.':'메뉴를 숨겼어요.')})}
function openMenuEditor(id){const existing=id?drinks.find(x=>x.id===id):null;const d=existing||{id:`menu-${Date.now()}`,category:'칵테일',name:'',price:13000,abv:'',desc:'',recommended:false,active:true,tags:[]};openModal(`<div class="detail-title"><p class="eyebrow">MENU EDITOR</p><h2>${existing?'메뉴 수정':'새 메뉴 추가'}</h2></div><form id="menuEditForm" class="menu-edit-form"><label>메뉴명<input name="name" value="${escapeHtml(d.name)}" required></label><div class="form-grid"><label>카테고리<select name="category">${CATEGORY_ORDER.map(c=>`<option ${c===d.category?'selected':''}>${c}</option>`).join('')}</select></label><label>가격<input name="price" type="number" min="0" step="100" value="${d.price}" required></label></div><label>도수 표기<input name="abv" value="${escapeHtml(d.abv||'')}" placeholder="예: 12~14도 / 논알콜"></label><label>한 줄 설명<textarea name="desc" required>${escapeHtml(d.desc)}</textarea></label><label class="toggle-line">사이 추천 표시<input name="recommended" type="checkbox" ${d.recommended?'checked':''}></label><label class="toggle-line">손님 메뉴판에 판매 중으로 표시<input name="active" type="checkbox" ${d.active!==false?'checked':''}></label><button class="primary full" type="submit">저장하기</button>${existing?'<button class="ghost full danger" type="button" id="deleteMenuItem">메뉴 삭제</button>':''}</form>`);$('#menuEditForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(d,{name:f.get('name').trim(),category:f.get('category'),price:Number(f.get('price')),abv:f.get('abv').trim(),desc:f.get('desc').trim(),recommended:f.get('recommended')==='on',active:f.get('active')==='on'});if(!existing)drinks.push(d);saveDrinks();closeModal();showToast(existing?'메뉴를 수정했어요.':'새 메뉴를 추가했어요.')};if(existing)$('#deleteMenuItem').onclick=()=>{if(confirm(`${d.name} 메뉴를 삭제할까요?`)){drinks=drinks.filter(x=>x.id!==d.id);saveDrinks();closeModal();showToast('메뉴를 삭제했어요.')}}}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#addMenuItem').onclick=()=>openMenuEditor();$('#resetMenu').onclick=()=>{if(confirm('수정한 메뉴를 모두 지우고 기본 메뉴판으로 되돌릴까요?')){drinks=structuredClone(DEFAULT_DRINKS);saveDrinks();showToast('기본 메뉴판으로 되돌렸어요.')}};
renderTabs();renderMenu();renderAtmosphere();
